// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"StructForge/backend/apps/user/internal/biz"
	"StructForge/backend/apps/user/internal/conf"
	"StructForge/backend/apps/user/internal/data"
	"StructForge/backend/apps/user/internal/server"
	"StructForge/backend/apps/user/internal/service"
	"StructForge/backend/common/data/database"
	"StructForge/backend/common/email"
	log2 "StructForge/backend/common/log"
	"context"
	"fmt"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"os"
	"time"
)

// Injectors from wire.go:

// wireApp 初始化应用（Wire 会自动生成 wire_gen.go）
func wireApp(bc *conf.Bootstrap) (*kratos.App, func(), error) {
	logger := logProvider()
	database, cleanup, err := databaseProvider()
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(database)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	userProfileRepo := data.NewUserProfileRepo(dataData)
	emailVerificationRepo := data.NewEmailVerificationRepo(dataData)
	emailService := emailProvider()
	userUseCase := biz.NewUserUseCase(userRepo, userProfileRepo, emailVerificationRepo, emailService)
	string2 := jwtSecretKeyProvider()
	duration := jwtTokenDurationProvider()
	jwtManager := biz.NewJWTManager(string2, duration)
	userService := service.NewUserService(userUseCase, jwtManager)
	grpcServer := server.NewGRPCServer(bc, userService)
	httpServer := server.NewHTTPServer(bc, userService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// emailProvider 提供邮件服务实例
func emailProvider() email.EmailService {

	config := email.DefaultConfig()

	return email.NewEmailService(config)
}

// jwtSecretKeyProvider 提供 JWT 密钥
func jwtSecretKeyProvider() string {

	return "your-secret-key-change-in-production"
}

// jwtTokenDurationProvider 提供 JWT Token 有效期
func jwtTokenDurationProvider() time.Duration {

	return 24 * time.Hour
}

// logProvider 提供日志实例（返回 Kratos 兼容的日志接口）
func logProvider() log.Logger {

	config := log2.DefaultConfig()
	config.ServiceName = "user"
	logger, err := log2.NewLogger(config)
	if err != nil {

		return log.NewStdLogger(os.Stderr)
	}
	log2.SetGlobalLogger(logger)

	return newKratosLogAdapter(logger)
}

// kratosLogAdapter 适配器，将我们的日志接口适配到 Kratos 日志接口
type kratosLogAdapter struct {
	logger log2.Logger
}

// newKratosLogAdapter 创建 Kratos 日志适配器
func newKratosLogAdapter(logger log2.Logger) log.Logger {
	return &kratosLogAdapter{logger: logger}
}

// Log 实现 Kratos Logger 接口
func (a *kratosLogAdapter) Log(level log.Level, keyvals ...interface{}) error {
	// 将 Kratos 日志级别转换为我们的日志级别
	var logLevel log2.Level
	switch level {
	case log.LevelDebug:
		logLevel = log2.DebugLevel
	case log.LevelInfo:
		logLevel = log2.InfoLevel
	case log.LevelWarn:
		logLevel = log2.WarnLevel
	case log.LevelError:
		logLevel = log2.ErrorLevel
	case log.LevelFatal:
		logLevel = log2.FatalLevel
	default:
		logLevel = log2.InfoLevel
	}

	msg := ""
	fields := make([]log2.Field, 0)
	for i := 0; i < len(keyvals); i += 2 {
		if i+1 < len(keyvals) {
			key := keyvals[i]
			val := keyvals[i+1]
			if keyStr, ok := key.(string); ok {
				if keyStr == "msg" {
					if msgStr, ok := val.(string); ok {
						msg = msgStr
					}
				} else {

					switch v := val.(type) {
					case string:
						fields = append(fields, log2.String(keyStr, v))
					case int:
						fields = append(fields, log2.Int(keyStr, v))
					case int64:
						fields = append(fields, log2.Int64(keyStr, v))
					case bool:
						fields = append(fields, log2.Bool(keyStr, v))
					case error:
						fields = append(fields, log2.ErrorField(v))
					default:
						fields = append(fields, log2.Any(keyStr, v))
					}
				}
			}
		}
	}

	if msg == "" {
		msg = "log message"
	}

	ctx := context.Background()
	a.logger.Log(ctx, logLevel, msg, fields...)
	return nil
}

// databaseProvider 提供数据库实例
func databaseProvider() (database.Database, func(), error) {
	db := database.GetGlobalDB()
	if db == nil {

		return nil, nil, fmt.Errorf("数据库未初始化，请在 main.go 中先调用 database.InitDatabaseFromFile")
	}
	return db, func() {}, nil
}

// newApp 创建应用实例
func newApp(
	logger log.Logger,
	grpcServer *server.GRPCServer,
	httpServer *server.HTTPServer,
) *kratos.App {
	return kratos.New(kratos.Name("user"), kratos.Version("v1.0.0"), kratos.Logger(logger), kratos.Server(
		grpcServer,
		httpServer,
	),
	)
}
