// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"StructForge/backend/apps/gateway/internal/conf"
	"StructForge/backend/apps/gateway/internal/handler"
	"StructForge/backend/apps/gateway/internal/middleware/metrics"
	"StructForge/backend/apps/gateway/internal/router"
	"StructForge/backend/apps/gateway/internal/server"
	"github.com/go-kratos/kratos/v2"
)

// Injectors from wire.go:

// wireApp 初始化应用（由 Wire 生成）
// 注意：此文件只在 wireinject 构建标签下编译
// 运行 wire 命令后会生成 wire_gen.go 文件
func wireApp(bc *conf.Bootstrap, redis *conf.Redis) (*kratos.App, func(), error) {
	gatewayConfig := getGatewayConfig(bc)
	corsHandler := router.NewCORSHandlerFromConfig(gatewayConfig)
	httpServer := server.NewHTTPServer(bc, corsHandler)
	staticDiscovery := router.NewStaticDiscovery()
	routerRouter, err := router.LoadRouterFromConfig(gatewayConfig, staticDiscovery)
	if err != nil {
		return nil, nil, err
	}
	manager := router.NewJWTManagerFromConfig(gatewayConfig)
	metricsMetrics := metrics.NewMetrics()
	metricsMiddleware := metrics.NewMetricsMiddleware(metricsMetrics)
	gatewayHandler := handler.NewGatewayHandler(routerRouter, manager, corsHandler, metricsMiddleware)
	dashboardHandler := handler.NewDashboardHandler()
	logger := newLogger()
	app := newApp(bc, httpServer, gatewayHandler, dashboardHandler, logger)
	return app, func() {
	}, nil
}
