// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package main

import (
	"StructForge/backend/apps/gateway/internal/conf"
	"StructForge/backend/apps/gateway/internal/handler"
	"StructForge/backend/apps/gateway/internal/server"

	"github.com/go-kratos/kratos/v2"
)

// wireApp 初始化应用
func wireApp(bc *conf.Bootstrap, redis *conf.Redis) (*kratos.App, func(), error) {
	logger := newLogger()
	httpServer := server.NewHTTPServer(bc)
	gatewayHandler := handler.NewGatewayHandler()
	app := newApp(bc, httpServer, gatewayHandler, logger)
	cleanup := func() {
		// 清理资源
	}
	return app, cleanup, nil
}
