// Code generated by protoc-gen-go. DO NOT EDIT.
// This file is a placeholder for generated configuration structures.
// In a real project, this would be generated from .proto files using protoc.

package conf

// Bootstrap 应用启动配置
type Bootstrap struct {
	// 服务器配置
	Server *Server `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// 数据库配置
	Database *Database `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	// Nacos 配置
	Nacos *Nacos `protobuf:"bytes,3,opt,name=nacos,proto3" json:"nacos,omitempty"`
}

// Server 服务器配置
type Server struct {
	// 服务ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 服务名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 服务版本
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// HTTP 配置
	Http *HTTP `protobuf:"bytes,4,opt,name=http,proto3" json:"http,omitempty"`
	// gRPC 配置
	Grpc *GRPC `protobuf:"bytes,5,opt,name=grpc,proto3" json:"grpc,omitempty"`
}

// HTTP HTTP服务器配置
type HTTP struct {
	// 监听地址
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// 超时时间（秒）
	Timeout int64 `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

// GRPC gRPC服务器配置
type GRPC struct {
	// 监听地址
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// 超时时间（秒）
	Timeout int64 `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

// Database 数据库配置（引用 common/data/database 的配置）
type Database struct {
	// 适配器类型
	AdapterType string `protobuf:"bytes,1,opt,name=adapter_type,json=adapterType,proto3" json:"adapter_type,omitempty"`
}

// Nacos Nacos配置
type Nacos struct {
	// 服务器配置列表
	ServerConfigs []*NacosServerConfig `protobuf:"bytes,1,rep,name=server_configs,json=serverConfigs,proto3" json:"server_configs,omitempty"`
	// 客户端配置
	ClientConfig *NacosClientConfig `protobuf:"bytes,2,opt,name=client_config,json=clientConfig,proto3" json:"client_config,omitempty"`
	// 配置中心配置
	ConfigCenter *NacosConfigCenter `protobuf:"bytes,3,opt,name=config_center,json=configCenter,proto3" json:"config_center,omitempty"`
}

// NacosServerConfig Nacos服务器配置
type NacosServerConfig struct {
	IpAddr      string `protobuf:"bytes,1,opt,name=ip_addr,json=ipAddr,proto3" json:"ip_addr,omitempty"`
	Port        uint64 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	ContextPath string `protobuf:"bytes,3,opt,name=context_path,json=contextPath,proto3" json:"context_path,omitempty"`
	Scheme      string `protobuf:"bytes,4,opt,name=scheme,proto3" json:"scheme,omitempty"`
}

// NacosClientConfig Nacos客户端配置
type NacosClientConfig struct {
	NamespaceId         string `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	TimeoutMs           uint64 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	NotLoadCacheAtStart bool   `protobuf:"varint,3,opt,name=not_load_cache_at_start,json=notLoadCacheAtStart,proto3" json:"not_load_cache_at_start,omitempty"`
	LogDir              string `protobuf:"bytes,4,opt,name=log_dir,json=logDir,proto3" json:"log_dir,omitempty"`
	CacheDir            string `protobuf:"bytes,5,opt,name=cache_dir,json=cacheDir,proto3" json:"cache_dir,omitempty"`
	LogLevel            string `protobuf:"bytes,6,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	Username            string `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	Password            string `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	AccessKey           string `protobuf:"bytes,9,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey           string `protobuf:"bytes,10,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
}

// NacosConfigCenter Nacos配置中心配置
type NacosConfigCenter struct {
	Enabled   bool   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	DataId    string `protobuf:"bytes,2,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Group     string `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
}
