// Code generated by protoc-gen-go. DO NOT EDIT.
// This file is a placeholder for generated configuration structures.
// In a real project, this would be generated from .proto files using protoc.

package conf

// Bootstrap 应用启动配置
type Bootstrap struct {
	// 服务器配置
	Server *Server `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// Redis 配置
	Redis *Redis `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
}

// Server 服务器配置
type Server struct {
	// 服务ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 服务名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 服务版本
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

// Redis Redis配置
type Redis struct {
	// Redis地址
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// 数据库编号
	Db int32 `protobuf:"varint,2,opt,name=db,proto3" json:"db,omitempty"`
	// 密码
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}
